eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
okta:
  oauth2:
    issuer: https://dev-21709836.okta.com/oauth2/default
    audience: api://default
